# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/network/device_config.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class DeviceConfigSpecSpec(betterproto.Message):
    """
    DeviceConfigSpecSpec is the spec for the network.DeviceConfigSpec resource.
    """

    yaml_marshalled: bytes = betterproto.bytes_field(1)
    """
    Contains YAML marshalled device config (as part of the machine config).
    """
