# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/cluster/cluster.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from ..... import common as ____common__
from .. import enums as _enums__


@dataclass(eq=False, repr=False)
class AffiliateSpec(betterproto.Message):
    """AffiliateSpec describes Affiliate state."""

    node_id: str = betterproto.string_field(1)
    addresses: List["____common__.NetIp"] = betterproto.message_field(2)
    hostname: str = betterproto.string_field(3)
    nodename: str = betterproto.string_field(4)
    operating_system: str = betterproto.string_field(5)
    machine_type: "_enums__.MachineType" = betterproto.enum_field(6)
    kube_span: "KubeSpanAffiliateSpec" = betterproto.message_field(7)
    control_plane: "ControlPlane" = betterproto.message_field(8)


@dataclass(eq=False, repr=False)
class ConfigSpec(betterproto.Message):
    """ConfigSpec describes KubeSpan configuration."""

    discovery_enabled: bool = betterproto.bool_field(1)
    registry_kubernetes_enabled: bool = betterproto.bool_field(2)
    registry_service_enabled: bool = betterproto.bool_field(3)
    service_endpoint: str = betterproto.string_field(4)
    service_endpoint_insecure: bool = betterproto.bool_field(5)
    service_encryption_key: bytes = betterproto.bytes_field(6)
    service_cluster_id: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class ControlPlane(betterproto.Message):
    """ControlPlane describes ControlPlane data if any."""

    api_server_port: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class IdentitySpec(betterproto.Message):
    """
    IdentitySpec describes status of rendered secrets. Note: IdentitySpec is
    persisted on disk in the STATE partition, so YAML serialization should be
    kept backwards compatible.
    """

    node_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class InfoSpec(betterproto.Message):
    """InfoSpec describes cluster information."""

    cluster_id: str = betterproto.string_field(1)
    cluster_name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class KubeSpanAffiliateSpec(betterproto.Message):
    """
    KubeSpanAffiliateSpec describes additional information specific for the
    KubeSpan.
    """

    public_key: str = betterproto.string_field(1)
    address: "____common__.NetIp" = betterproto.message_field(2)
    additional_addresses: List["____common__.NetIpPrefix"] = betterproto.message_field(
        3
    )
    endpoints: List["____common__.NetIpPort"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class MemberSpec(betterproto.Message):
    """MemberSpec describes Member state."""

    node_id: str = betterproto.string_field(1)
    addresses: List["____common__.NetIp"] = betterproto.message_field(2)
    hostname: str = betterproto.string_field(3)
    machine_type: "_enums__.MachineType" = betterproto.enum_field(4)
    operating_system: str = betterproto.string_field(5)
    control_plane: "ControlPlane" = betterproto.message_field(6)
