# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/extensions/extensions.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Compatibility(betterproto.Message):
    """Compatibility describes extension compatibility."""

    talos: "Constraint" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Constraint(betterproto.Message):
    """Constraint describes compatibility constraint."""

    version: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class Layer(betterproto.Message):
    """Layer defines overlay mount layer."""

    image: str = betterproto.string_field(1)
    metadata: "Metadata" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Metadata(betterproto.Message):
    """Metadata describes base extension metadata."""

    name: str = betterproto.string_field(1)
    version: str = betterproto.string_field(2)
    author: str = betterproto.string_field(3)
    description: str = betterproto.string_field(4)
    compatibility: "Compatibility" = betterproto.message_field(5)
