# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/hardware/hardware.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class MemoryModuleSpec(betterproto.Message):
    """MemoryModuleSpec represents a single Memory."""

    size: int = betterproto.uint32_field(1)
    device_locator: str = betterproto.string_field(2)
    bank_locator: str = betterproto.string_field(3)
    speed: int = betterproto.uint32_field(4)
    manufacturer: str = betterproto.string_field(5)
    serial_number: str = betterproto.string_field(6)
    asset_tag: str = betterproto.string_field(7)
    product_name: str = betterproto.string_field(8)


@dataclass(eq=False, repr=False)
class ProcessorSpec(betterproto.Message):
    """ProcessorSpec represents a single processor."""

    socket: str = betterproto.string_field(1)
    manufacturer: str = betterproto.string_field(2)
    product_name: str = betterproto.string_field(3)
    max_speed: int = betterproto.uint32_field(4)
    boot_speed: int = betterproto.uint32_field(5)
    status: int = betterproto.uint32_field(6)
    serial_number: str = betterproto.string_field(7)
    asset_tag: str = betterproto.string_field(8)
    part_number: str = betterproto.string_field(9)
    core_count: int = betterproto.uint32_field(10)
    core_enabled: int = betterproto.uint32_field(11)
    thread_count: int = betterproto.uint32_field(12)


@dataclass(eq=False, repr=False)
class SystemInformationSpec(betterproto.Message):
    """
    SystemInformationSpec represents the system information obtained from
    smbios.
    """

    manufacturer: str = betterproto.string_field(1)
    product_name: str = betterproto.string_field(2)
    version: str = betterproto.string_field(3)
    serial_number: str = betterproto.string_field(4)
    uuid: str = betterproto.string_field(5)
    wake_up_type: str = betterproto.string_field(6)
    sku_number: str = betterproto.string_field(7)
