# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/proto/proto.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class LinuxIdMapping(betterproto.Message):
    """LinuxIDMapping specifies UID/GID mappings."""

    container_id: int = betterproto.uint32_field(1)
    host_id: int = betterproto.uint32_field(2)
    size: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class Mount(betterproto.Message):
    """Mount specifies a mount for a container."""

    destination: str = betterproto.string_field(1)
    type: str = betterproto.string_field(2)
    source: str = betterproto.string_field(3)
    options: List[str] = betterproto.string_field(4)
    uid_mappings: List["LinuxIdMapping"] = betterproto.message_field(5)
    gid_mappings: List["LinuxIdMapping"] = betterproto.message_field(6)
