# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/runtime/runtime.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from ..... import common as ____common__
from .. import enums as _enums__


@dataclass(eq=False, repr=False)
class DevicesStatusSpec(betterproto.Message):
    """DevicesStatusSpec is the spec for devices status."""

    ready: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class EventSinkConfigSpec(betterproto.Message):
    """
    EventSinkConfigSpec describes configuration of Talos event log streaming.
    """

    endpoint: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class KernelModuleSpecSpec(betterproto.Message):
    """KernelModuleSpecSpec describes Linux kernel module to load."""

    name: str = betterproto.string_field(1)
    parameters: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class KernelParamSpecSpec(betterproto.Message):
    """KernelParamSpecSpec describes status of the defined sysctls."""

    value: str = betterproto.string_field(1)
    ignore_errors: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class KernelParamStatusSpec(betterproto.Message):
    """KernelParamStatusSpec describes status of the defined sysctls."""

    current: str = betterproto.string_field(1)
    default: str = betterproto.string_field(2)
    unsupported: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class KmsgLogConfigSpec(betterproto.Message):
    """KmsgLogConfigSpec describes configuration for kmsg log streaming."""

    destinations: List["____common__.Url"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class MachineStatusSpec(betterproto.Message):
    """MachineStatusSpec describes status of the defined sysctls."""

    stage: "_enums__.RuntimeMachineStage" = betterproto.enum_field(1)
    status: "MachineStatusStatus" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class MachineStatusStatus(betterproto.Message):
    """MachineStatusStatus describes machine current status at the stage."""

    ready: bool = betterproto.bool_field(1)
    unmet_conditions: List["UnmetCondition"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class MaintenanceServiceConfigSpec(betterproto.Message):
    """
    MaintenanceServiceConfigSpec describes configuration for maintenance
    service API.
    """

    listen_address: str = betterproto.string_field(1)
    reachable_addresses: List["____common__.NetIp"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class MetaKeySpec(betterproto.Message):
    """MetaKeySpec describes status of the defined sysctls."""

    value: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class MetaLoadedSpec(betterproto.Message):
    """
    MetaLoadedSpec is the spec for meta loaded. The Done field is always true
    when resource exists.
    """

    done: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class MountStatusSpec(betterproto.Message):
    """MountStatusSpec describes status of the defined sysctls."""

    source: str = betterproto.string_field(1)
    target: str = betterproto.string_field(2)
    filesystem_type: str = betterproto.string_field(3)
    options: List[str] = betterproto.string_field(4)
    encrypted: bool = betterproto.bool_field(5)
    encryption_providers: List[str] = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class PlatformMetadataSpec(betterproto.Message):
    """PlatformMetadataSpec describes platform metadata properties."""

    platform: str = betterproto.string_field(1)
    hostname: str = betterproto.string_field(2)
    region: str = betterproto.string_field(3)
    zone: str = betterproto.string_field(4)
    instance_type: str = betterproto.string_field(5)
    instance_id: str = betterproto.string_field(6)
    provider_id: str = betterproto.string_field(7)
    spot: bool = betterproto.bool_field(8)


@dataclass(eq=False, repr=False)
class SecurityStateSpec(betterproto.Message):
    """SecurityStateSpec describes the security state resource properties."""

    secure_boot: bool = betterproto.bool_field(1)
    uki_signing_key_fingerprint: str = betterproto.string_field(2)
    pcr_signing_key_fingerprint: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class UniqueMachineTokenSpec(betterproto.Message):
    """
    UniqueMachineTokenSpec is the spec for the machine unique token. Token can
    be empty if machine wasn't assigned any.
    """

    token: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class UnmetCondition(betterproto.Message):
    """
    UnmetCondition is a failure which prevents machine from being ready at the
    stage.
    """

    name: str = betterproto.string_field(1)
    reason: str = betterproto.string_field(2)
