# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/time/time.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class StatusSpec(betterproto.Message):
    """StatusSpec describes time sync state."""

    synced: bool = betterproto.bool_field(1)
    epoch: int = betterproto.int64_field(2)
    sync_disabled: bool = betterproto.bool_field(3)
