# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/files/files.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class EtcFileSpecSpec(betterproto.Message):
    """EtcFileSpecSpec describes status of rendered secrets."""

    contents: bytes = betterproto.bytes_field(1)
    mode: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class EtcFileStatusSpec(betterproto.Message):
    """EtcFileStatusSpec describes status of rendered secrets."""

    spec_version: str = betterproto.string_field(1)
