# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/v1alpha1/v1alpha1.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class ServiceSpec(betterproto.Message):
    """ServiceSpec describe service state."""

    running: bool = betterproto.bool_field(1)
    healthy: bool = betterproto.bool_field(2)
    unknown: bool = betterproto.bool_field(3)
