# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/siderolink/siderolink.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class ConfigSpec(betterproto.Message):
    """ConfigSpec describes KubeSpan configuration.."""

    api_endpoint: str = betterproto.string_field(1)
