# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/cri/cri.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf


@dataclass(eq=False, repr=False)
class SeccompProfileSpec(betterproto.Message):
    """SeccompProfileSpec represents the SeccompProfile."""

    name: str = betterproto.string_field(1)
    value: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(2)
