# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/config/config.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class MachineType(betterproto.Enum):
    """MachineType matches machine.Type constants."""

    UNKNOWN = 0
    INIT = 1
    CONTROL_PLANE = 2
    WORKER = 3


@dataclass(eq=False, repr=False)
class MachineConfigSpec(betterproto.Message):
    """MessageConfigSpec is the spec for the config.MachineConfig resource."""

    yaml_marshalled: bytes = betterproto.bytes_field(1)
    """
    Contains YAML marshalled machine configuration. Byte representation is
    preserved as the machine configuration was submitted to the node.
    """


@dataclass(eq=False, repr=False)
class MachineTypeSpec(betterproto.Message):
    """MachineTypeSpec is the spec for the config.MachineType resource."""

    machine_type: "MachineType" = betterproto.enum_field(1)
