# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resource/definitions/kubeaccess/kubeaccess.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class ConfigSpec(betterproto.Message):
    """ConfigSpec describes KubeSpan configuration.."""

    enabled: bool = betterproto.bool_field(1)
    allowed_api_roles: List[str] = betterproto.string_field(2)
    allowed_kubernetes_namespaces: List[str] = betterproto.string_field(3)
